name: project_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy
  - tensorflow
  - pillow
  - opencv
  - ipython
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - wordcloud
  - papermill
  - ipywidgets>=7.5.1
  - pip:
    - google-generativeai
